export const routes = ["Home", "Services", "Contact", "Blog"];

export const skillset = [
  "React",
  "Next.js",
  "JavaScript",
  "TypeScript",
  "Python",
  "Flask",
  "FastAPI",
  "Tailwind CSS",
  "Git",
  "Supabase",
  "Firebase",
  "Node.js",
  "Express.js",
  "MongoDB",
  "SQL",
  "Cypress",
  "Zustand",
  "GraphQL",
  "Docker",
  "REST API",
  "Linux",
];
